/*
 * Copyright 2026 frikiT
 *
 * Licensed under the Apache License, Version 2.0 (the "License");
 * you may not use this file except in compliance with the License.
 * You may obtain a copy of the License at
 *
 *     http://www.apache.org/licenses/LICENSE-2.0
 *
 * Unless required by applicable law or agreed to in writing, software
 * distributed under the License is distributed on an "AS IS" BASIS,
 * WITHOUT WARRANTIES OR CONDITIONS OF ANY KIND, either express or implied.
 * See the License for the specific language governing permissions and
 * limitations under the License.
 */

package io.github.frikit.twirlspec.html

/** The parts of the HTML vocabulary a checker needs to know to tell a mistake
  * from a shorthand.
  */
object HtmlVocabulary {

  /** Elements that never have content, so never have an end tag. */
  val void: Set[String] = Set(
    "area",
    "base",
    "br",
    "col",
    "embed",
    "hr",
    "img",
    "input",
    "link",
    "meta",
    "param",
    "source",
    "track",
    "wbr"
  )

  /** Elements whose end tag the HTML specification allows you to leave out.
    *
    * `<div><p>text</div>` is not a mistake: the `</div>` closes the paragraph
    * for you. A checker that does not know this reports half of every page.
    */
  val optionalEndTag: Set[String] = Set(
    "p",
    "li",
    "dt",
    "dd",
    "option",
    "optgroup",
    "thead",
    "tbody",
    "tfoot",
    "tr",
    "td",
    "th",
    "rt",
    "rp",
    "colgroup",
    "caption",
    "head",
    "body",
    "html"
  )

  /** Elements whose content is text, not markup: a `<` inside them opens
    * nothing.
    */
  val rawText: Set[String] = Set("script", "style", "textarea", "title")

  /** Every element name in the HTML living standard. */
  val elements: Set[String] = Set(
    "a",
    "abbr",
    "address",
    "area",
    "article",
    "aside",
    "audio",
    "b",
    "base",
    "bdi",
    "bdo",
    "blockquote",
    "body",
    "br",
    "button",
    "canvas",
    "caption",
    "cite",
    "code",
    "col",
    "colgroup",
    "data",
    "datalist",
    "dd",
    "del",
    "details",
    "dfn",
    "dialog",
    "div",
    "dl",
    "dt",
    "em",
    "embed",
    "fieldset",
    "figcaption",
    "figure",
    "footer",
    "form",
    "h1",
    "h2",
    "h3",
    "h4",
    "h5",
    "h6",
    "head",
    "header",
    "hgroup",
    "hr",
    "html",
    "i",
    "iframe",
    "img",
    "input",
    "ins",
    "kbd",
    "label",
    "legend",
    "li",
    "link",
    "main",
    "map",
    "mark",
    "menu",
    "meta",
    "meter",
    "nav",
    "noscript",
    "object",
    "ol",
    "optgroup",
    "option",
    "output",
    "p",
    "picture",
    "pre",
    "progress",
    "q",
    "rp",
    "rt",
    "ruby",
    "s",
    "samp",
    "script",
    "search",
    "section",
    "select",
    "slot",
    "small",
    "source",
    "span",
    "strong",
    "style",
    "sub",
    "summary",
    "sup",
    "table",
    "tbody",
    "td",
    "template",
    "textarea",
    "tfoot",
    "th",
    "thead",
    "time",
    "title",
    "tr",
    "track",
    "u",
    "ul",
    "var",
    "video",
    "wbr",
    // SVG and MathML roots and the handful of children that appear inline in page markup
    "svg",
    "path",
    "circle",
    "rect",
    "g",
    "defs",
    "use",
    "line",
    "polygon",
    "polyline",
    "ellipse",
    "text",
    "tspan",
    "math",
    "mi",
    "mn",
    "mo",
    "mrow",
    "msup",
    "msub"
  )

  /** Attributes any element may carry. */
  val globalAttributes: Set[String] = Set(
    "accesskey",
    "autocapitalize",
    "autofocus",
    "class",
    "contenteditable",
    "dir",
    "draggable",
    "enterkeyhint",
    "hidden",
    "id",
    "inert",
    "inputmode",
    "is",
    "itemid",
    "itemprop",
    "itemref",
    "itemscope",
    "itemtype",
    "lang",
    "nonce",
    "popover",
    "slot",
    "spellcheck",
    "style",
    "tabindex",
    "title",
    "translate",
    "role",
    "part",
    "exportparts"
  )

  /** Attributes that belong to particular elements. Kept flat: a checker that
    * knows the name is real catches the typo, and which element it sits on is
    * the content model's business rather than the vocabulary's.
    */
  val elementAttributes: Set[String] = Set(
    "abbr",
    "accept",
    "accept-charset",
    "action",
    "allow",
    "allowfullscreen",
    "alt",
    "as",
    "async",
    "autocomplete",
    "autoplay",
    "background",
    "blocking",
    "border",
    "capture",
    "charset",
    "checked",
    "cite",
    "cols",
    "colspan",
    "content",
    "controls",
    "coords",
    "crossorigin",
    "data",
    "datetime",
    "decoding",
    "default",
    "defer",
    "disabled",
    "download",
    "enctype",
    "fetchpriority",
    "for",
    "form",
    "formaction",
    "formenctype",
    "formmethod",
    "formnovalidate",
    "formtarget",
    "headers",
    "height",
    "high",
    "href",
    "hreflang",
    "http-equiv",
    "imagesizes",
    "imagesrcset",
    "integrity",
    "ismap",
    "kind",
    "label",
    "list",
    "loading",
    "loop",
    "low",
    "max",
    "maxlength",
    "media",
    "method",
    "min",
    "minlength",
    "multiple",
    "muted",
    "name",
    "novalidate",
    "open",
    "optimum",
    "pattern",
    "ping",
    "placeholder",
    "playsinline",
    "poster",
    "preload",
    "readonly",
    "referrerpolicy",
    "rel",
    "required",
    "reversed",
    "rows",
    "rowspan",
    "sandbox",
    "scope",
    "selected",
    "shape",
    "size",
    "sizes",
    "span",
    "src",
    "srcdoc",
    "srclang",
    "srcset",
    "start",
    "step",
    "target",
    "type",
    "usemap",
    "value",
    "width",
    "wrap",
    // RDFa, microdata and SVG presentation, all of which appear in GOV.UK page markup
    "nomodule",
    "dirname",
    "autocorrect",
    "color",
    "rx",
    "ry",
    "dx",
    "dy",
    "xmlns:xlink",
    "opacity",
    "fill-opacity",
    "fill-rule",
    "clip-rule",
    "clip-path",
    "stroke-opacity",
    "stroke-linecap",
    "stroke-linejoin",
    "stroke-dasharray",
    "stroke-dashoffset",
    "stroke-miterlimit",
    "vector-effect",
    "shape-rendering",
    "text-anchor",
    "dominant-baseline",
    "font-family",
    "font-size",
    "font-weight",
    "text-rendering",
    "mask",
    "offset",
    "stop-color",
    "stop-opacity",
    "gradientunits",
    "patternunits",
    "property",
    "about",
    "typeof",
    "vocab",
    "resource",
    "prefix",
    "datatype",
    "rev",
    // svg
    "viewbox",
    "d",
    "fill",
    "stroke",
    "stroke-width",
    "cx",
    "cy",
    "r",
    "x",
    "y",
    "x1",
    "y1",
    "x2",
    "y2",
    "points",
    "transform",
    "focusable",
    "aria-hidden",
    "xmlns",
    "preserveaspectratio"
  )

  /** Whether the HTML specification defines an element with this name. */
  def isKnownElement(name: String): Boolean =
    elements.contains(name.toLowerCase)

  /** `data-*` and `aria-*` are open sets by design, and a framework may add its
    * own prefix.
    */
  def isKnownAttribute(name: String, extraPrefixes: Set[String]): Boolean = {
    val n = name.toLowerCase
    n.startsWith("data-") || n.startsWith("aria-") || extraPrefixes.exists(
      n.startsWith
    ) ||
    globalAttributes.contains(n) || elementAttributes.contains(n)
  }

}
